"""auth

Revision ID: 9938fabcd46b
Revises: ecfdcdf84380
Create Date: 2025-07-15 13:58:39.507891

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9938fabcd46b"
down_revision: Union[str, Sequence[str], None] = "ecfdcdf84380"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("hashed_password", sa.String(), nullable=False, server_default=""),
    )
    op.alter_column("users", "hashed_password", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###
