"""reate users, wallets and operations tables

Revision ID: ecfdcdf84380
Revises: b5bb3a9bd36f
Create Date: 2025-07-15 12:36:43.875739

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ecfdcdf84380"
down_revision: Union[str, Sequence[str], None] = "b5bb3a9bd36f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "operations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("wallet_id", sa.UUID(), nullable=False),
        sa.Column(
            "operation_type",
            sa.Enum("DEPOSIT", "WITHDRAW", name="operationtype"),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["wallets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("wallets", sa.Column("user_id", sa.UUID(), nullable=False))
    op.alter_column(
        "wallets",
        "balance",
        existing_type=sa.NUMERIC(precision=18, scale=2),
        type_=sa.Numeric(precision=12, scale=2),
        nullable=False,
    )
    op.create_foreign_key(None, "wallets", "users", ["user_id"], ["id"])
    op.drop_column("wallets", "currency")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wallets",
        sa.Column("currency", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "wallets", type_="foreignkey")
    op.alter_column(
        "wallets",
        "balance",
        existing_type=sa.Numeric(precision=12, scale=2),
        type_=sa.NUMERIC(precision=18, scale=2),
        nullable=True,
    )
    op.drop_column("wallets", "user_id")
    op.drop_table("operations")
    op.drop_table("users")
    # ### end Alembic commands ###
